# Site settings
title: Careful Escapades
email: emil.hellman+careful@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hacks and tricks for software development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://archevel.github.io" # the base hostname & protocol for your site
twitter_username: archevel
github_username:  archevel

# Build settings
markdown: kramdown

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
